"""add tax rate to quote items

Revision ID: 2d9ab435d021
Revises: 74df86f00605
Create Date: 2026-08-11 19:24:56.245760

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2d9ab435d021"
down_revision: Union[str, Sequence[str], None] = "74df86f00605"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quote_items",
        sa.Column(
            "tax_rate",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
            server_default="19.00",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quote_items", "tax_rate")
    # ### end Alembic commands ###
